### ISSUE TITLE
Recovery screen after the .dfu(external.bin) injection

### ISSUE THREAD

**Issue by Data3rr** [TI-Planet/webdfu_numworks#8]
## What is the problem?
- When I use the webdfu on my numworks n0110 to downgrade 19.5 to 18.2 the injection works perfectly, except that when I unplug it and try to use the reset button it stays on the rescue page... Would you have a solution or do I just have to wait for a new hack. Have a nice day
## Screenshot
- The webdfu output
![Logo](https://imgur.com/L4Dq6p4.png)

**Comment by critor** [comment]
Which firmware was on the calculator before the v19 update ?

**Comment by Data3rr** [comment]
I received it last week and I updated it right away like a fool, I think it was a version 16

**Comment by critor** [comment]
Thanks.

If you did update to v19 from a v16, you _should_ be able to downgrade.

If you did update to v19 from a v15, the process does install a newer version of the bootloader which won't boot older versions of the firmware (thus the rescue screen).

**Comment by Data3rr** [comment]
Thanks 
Normally I'm supposed to be able to downgrade because I don't think my calculator was in 15 since I received it last week and normally the ones distributed for the 2022 school year were in v16. I don't understand why it keeps looping on the recovery screen ;).
